# Generated by Django 4.0.4 on 2022-05-13 17:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('credit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Naftal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NaftalWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_pay.company')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('plate', models.CharField(max_length=10, unique=True)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_pay.company')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('time', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_pay.company')),
                ('naftal_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_pay.naftalworker')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_pay.station')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_pay.worker')),
            ],
        ),
        migrations.AddField(
            model_name='naftalworker',
            name='id_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_pay.station'),
        ),
    ]
